# Makefile.deps created Mon May 15 05:18:34 PDT 2017 by gmake
astree.o: astree.cpp astree.h auxlib.h string_set.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp auxlib.h lyutils.h astree.h yyparse.h
string_set.o: string_set.cpp auxlib.h string_set.h
auxlib.o: auxlib.cpp auxlib.h
main.o: main.cpp astree.h auxlib.h lyutils.h yyparse.h string_set.h
yylex.o: yylex.cpp auxlib.h lyutils.h astree.h yyparse.h
yyparse.o: yyparse.cpp lyutils.h astree.h auxlib.h yyparse.h
